project4/network/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("profile/<user>", views.profile, name="profile"),
    path("edit/<user>", views.edit, name="edit"),
    path("like/<int:id>", views.like, name="like"),
]

project4/project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

project4/network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone

import datetime

class User(AbstractUser):
    pass


class Post(models.Model):
    """
    Model that stores all neccesary data for a post
    """

    content = models.CharField(max_length=400)
    user = models.ForeignKey('User', related_name="user_who_posted", on_delete=models.CASCADE)
    likes = models.IntegerField(default=0)
    timestamp = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.content

class Friendship(models.Model):
    root = models.ForeignKey(User, related_name="friendship_creator", on_delete=models.CASCADE)
    following = models.ForeignKey(User, related_name="friend_set", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.root} is following {self.following}"

class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True, on_delete=models.CASCADE)
    followers = models.IntegerField(default=0)
    following = models.IntegerField(default=0)
    description = models.CharField(max_length=400, default="I am an arbitrary user with zero personality...")

    def get_followers(self):
        user = self.user
        return Friendship.objects.filter(following=user)

    def __str__(self):
        return self.user.username

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    class Meta:
        unique_together = (('post', 'user'),)

    def __str__(self):
        return f"{self.post} : {self.user}"

project4/network/forms.py
from logging import PlaceHolder
from socket import fromshare
from django import forms

from .models import Post, UserProfile

class CreatePost(forms.ModelForm):
    def __init__(self, **kwargs):
        self.user = kwargs.pop('user', None)
        super(CreatePost, self).__init__(**kwargs)
        self.fields['content'].required = False

    def save(self, commit=True):
        obj = super(CreatePost, self).save(commit=False)
        obj.user = self.user
        if commit:
            obj.save()
        return obj

    content = forms.CharField(label='', widget=forms.TextInput(attrs={
        'placeholder': "What's going on...",
        'style': 'font-size: xx-large',
        'autocomplete': 'off',
        }), initial='')
    class Meta:
        model = Post
        fields = ['content']

project4/network/views.py
import json

from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponseBadRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.core.paginator import Paginator
from django.utils.decorators import method_decorator

from .models import Post, User, UserProfile, Friendship, Like
from .forms import CreatePost



def index(request):

    users = User.objects.all()

    ## Fetch all posts and display using Paginator
    objects = Post.objects.all().order_by('-timestamp')
    num_items = 10

    p = Paginator(objects, num_items)

    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)

    ## Handles New Post Submission
    if request.method == "POST":
        form = CreatePost(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("index"))
    else:
        form = CreatePost(user=request.user)

    return render(request, "network/index.html", {
        'all_users': users,
        'page_obj': page_obj,
        'form': form,
    })

def profile(request, user):
    # Generates correct user profile
    user = User.objects.get(username=user)
    user_profile = UserProfile.objects.get(user=user)

    # Creates a friendship between two users if user pressed "follow"
    if request.method == "POST":
        
        if Friendship.objects.filter(root=request.user, following=user).exists():
            # Delete the friendship
            Friendship.objects.filter(root=request.user, following=user).delete()

            # Update following count
            user_profile.followers -= 1
            user_profile.save()
        # If a friendship doesn't already exist, create one
        else: 
            n_friend = Friendship(root=request.user, following=user)
            n_friend.save()

            # Update following count
            user_profile.followers += 1
            user_profile.save()


    # Fetches friend list
    friends = user_profile.get_followers()
    friend_list = []

    for friend in friends:
        name = User.objects.get(username=friend.root)
        friend_list.append(name)
        

    # Displays correct button
    if request.user == user:
        button = 'edit'
    elif Friendship.objects.filter(root=request.user, following=user).exists():
        button = 'unfollow'
    else:
        button = 'follow'

    # Fetches all posts posted by the selected user
    posts = Post.objects.filter(user=user)

    return render(request, "network/profile.html", {
        'user': user,
        'button': button,  
        'profile': user_profile,
        'friends': friend_list,
        'posts': posts
    })

def edit(request, user):

    user = User.objects.get(username=user)
    e_profile = UserProfile.objects.get(user=user)

    if request.method == 'POST':
        q_dict = request.POST

        n_description = q_dict['description']
        e_profile.description = n_description
        e_profile.save()

    return render(request, "network/edit.html")

def like(request, id):

    if request.method == 'GET':
        css_class = 'fas fa-heart'
        post = Post.objects.get(id=id)
        like = Like.objects.get_or_create(
            user=request.user, post=post)

        if not like[1]:
            css_class = 'far fa-heart'
            Like.objects.filter(user=request.user, post=post).delete()

        total_likes = Like.objects.filter(post=post).count()
    return JsonResponse({
        "like": id, "css_class": css_class, "total_likes": total_likes
    })

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
            user_profile = UserProfile(user=user)
            user_profile.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "network/register.html")

project4/network/templates/network/index.html
{% extends "network/layout.html" %}
{% load static %}


{% block body %}

<!-- Page content-->
<div class="container">
  <div class="row col-gap">
    <!-- Page header with logo and tagline-->
    <header class="py-1 border-bottom mb-4">
      <div class="container">
          <div class="text-center my-5">

              <form action="" method="post" id="create_post">
                  {% csrf_token %}
                  {{ form.as_table }}
                  <input type="submit" value="Post" class="btn btn-primary">
              </form> 
          </div>
      </div>
      
      <!-- Blog entries-->
      <div class="col-md-6">
          <!-- Featured blog post-->
          <div class="card mb-4">
              <a href="#!"><img class="card-img-top" src="https://apastyle.apa.org/images/blog-whats-new-7e-tile_tcm11-270508.jpg" alt="..." /></a>
              <div class="card-body">
                  <div class="small text-muted">April 14, 2022</div>
                  <h2 class="card-title">What's new?</h2>
                  <p class="card-text">Coming soon!</p>
                  <a class="btn btn-primary" href="#!">Read more</a>
              </div>
          </div>

          <div class="row">
              <div class="col-lg-6">
                  <!-- Blog post-->
                  {% for post in page_obj %}
                    <div class="card mb-4" id="post">
                        <div class="card-body">
                            <div class="small text-muted">{{ post.timestamp }}</div>
                            <h2 class="card-title h4">{{ post.user }}</h2>
                            <p class="card-text">{{ post.content }}</p>

                            <!-- Like button -->
                            <p class="card-text">
                                <div data-id="{{post.id}}"
                                    class="card-link {% if post.current_like > 0 %} fas {%else%} far {% endif %} fa-heart">&nbsp<small
                                        class="text-muted">{{post.like_set.count}}</small>
                                        </div>
                            </p>
                        </div>
                    </div>
                    {% endfor %}

                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                          {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                          {% endif %}
                          <li class="page-item"><a class="page-link" href="#">1</a></li>
                          <li class="page-item"><a class="page-link" href="#">2</a></li>
                          <li class="page-item"><a class="page-link" href="#">3</a></li>
                          <!-- {% if page_obj.has_next %} -->

                          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                        </ul>
                          <!-- {% endif %} -->
                      </nav>
              </div>
          </div>
      </div>
          
      {% include "./side_widgets.html" %}
{% endblock %}

project4/network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">    </head>
    <body>       
        
        {% include "./navbar.html" %}
        

        {% block body %}
        {% endblock %}

        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Location</h4>
                        <p class="lead mb-0">
                            2215 John Daniel Drive
                            <br />
                            Clark, MO 65243
                        </p>
                    </div>
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Around the Web</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-linkedin-in"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-dribbble"></i></a>
                    </div>
                    <!-- Footer About Text-->
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">About Freelancer</h4>
                        <p class="lead mb-0">
                            Freelance is a free to use, MIT licensed Bootstrap theme created by
                            <a href="http://startbootstrap.com">Start Bootstrap</a>
                            .
                        </p>
                    </div>
                </div>
            </div>
        </footer>   
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright &copy; Your Website 2022</small></div>
        </div>
    </body>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="{% static 'network/index.js' %}"></script>
</html>

project4/network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

project4/network/templates/network/navbar.html
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#!">Network</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

</header>

project4/network/templates/network/profile.html
{% extends "network/layout.html" %}
{% load static %}
        
{% block body %}
<div class="container">
    <div class="row col-gap">
        <div class="card p-4">
            <div class=" image d-flex flex-column justify-content-center align-items-center"> <button class="btn btn-secondary"> <img src="https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg" height="100" width="100" /></button> <span class="name mt-3">{{ user.username }}</span> <span class="idd">{{ user.email }}</span>
                <div class="d-flex flex-row justify-content-center align-items-center mt-3"> <span class="number">{{ profile.followers  }} <span class="follow">Followers</span></span> </div>
                
                <!-- Logic for displaying edit/follow/unfollow -->
                <div class=" d-flex mt-2"> 
                    {% if button == "follow" %}
                    <form action="{% url 'profile' user.username %}" method="post">
                        {% csrf_token %}
                        <button class="btn1 btn-dark" id="follow">Follow</button> 
                    </form>
                    {% elif button == "edit" %}
                    <form action="{% url 'edit' user.username" method="get">
                        {% csrf_token %}
                        <button class="btn1 btn-dark">Edit Profile</button>
                    </form>
                        
                    {% else %}
                    <form action="{% url 'profile' user.username %}" method="post">
                        {% csrf_token %}
                        <button class="btn1 btn-dark">Unfollow</button>
                    </form>
                        
                    {% endif %}
                </div>            
                <div class="text mt-3"> <span>{{ profile.description }} </span> </div>
                <div class=" px-2 rounded mt-4 date "> <span class="join">{{ user.date_joined. }} </span> </div>
            </div>
        </div>
        <div class="card p-4">
            <div class=" image d-flex flex-column justify-content-center align-items-center">Followers</span>
                {% for friend in friends %}
                    <div class="d-flex flex-row justify-content-center align-items-center mt-3">
                        {{ friend }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    
    <!-- Displays user posts -->
    <div class="row">
        <div class="col-lg-6">
            <!-- Blog post-->
            {% for post in posts %}
              <div class="card mb-4" id="post">
                  <div class="card-body">
                      <div class="small text-muted">{{ post.timestamp }}</div>
                      <h2 class="card-title h4">{{ post.user }}</h2>
                      <p class="card-text">{{ post.content }}</p>
                  </div>
              </div>
              {% endfor %}

              <nav aria-label="Page navigation example">
                  <ul class="pagination">
                    {% if page_obj.has_previous %}
                      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                    {% endif %}
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <!-- {% if page_obj.has_next %} -->
                      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                    <!-- {% endif %} -->
                  </ul>
                </nav>
        </div>
    </div>
    
</div>
{% endblock %}

project4/network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

project4/network/templates/network/side_widgets.html
<!-- Side widgets-->
<div class="col-lg-6">
    <!-- Categories widget-->
    <div class="card mb-4">
        <div class="card-header">Categories</div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                    <ul class="list-unstyled mb-0">
                        <li><a href="#!">Web Design</a></li>
                        <li><a href="#!">HTML</a></li>
                        <li><a href="#!">Freebies</a></li>
                    </ul>
                </div>
                <div class="col-sm-6">
                    <ul class="list-unstyled mb-0">
                        <li><a href="#!">JavaScript</a></li>
                        <li><a href="#!">CSS</a></li>
                        <li><a href="#!">Tutorials</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Side widget-->
    <div class="card mb-4">
        <div class="card-header">Find Friends</div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                    <ul>
                        {% for user in all_users %}
                            <li><a href="{% url 'profile' user %}">{{ user }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</div>